services:
  db:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432

  application_backend:
    container_name: application_backend
    build: .
    ports:
      - 9091:9090
    environment:
      db-url: jdbc:postgresql://postgres_container:5432/postgres
      db-username: admin
      db-password: 1234
    depends_on:
      - db
