services:
  db:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432

  application_backend:
    container_name: application_backend
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_container:5432/postgres
    ports:
      - 9090:9090
    depends_on:
      - db